#!/bin/bash
#
# /etc/init.d/hadoop-rm -- startup script for Apache Hadoop
#
# Written by Dmytro Sukhariev <sukharevd@gmail.com>
#
### BEGIN INIT INFO
# Provides:             hadoop-rm
# Required-Start:       $remote_fs $network
# Required-Stop:        $remote_fs $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Apache Hadoop 2.2
# Description:          Provide Apache Hadoop ResourceManager startup/shutdown script
### END INIT INFO

. /etc/default/hadoop

case "$1" in
      
    start)
        # Start the YARN with the following command, run on the designated ResourceManager as yarn:
        echo 'Starting ResourceManager.'
        sudo -u $YARN_USER $HADOOP_YARN_HOME/sbin/yarn-daemon.sh --config $HADOOP_CONF_DIR start resourcemanager

        # Start the MapReduce JobHistory Server with the following command, run on the designated server as mapred:
        echo 'Starting historyserver.'
        sudo -u $MAPRED_USER $HADOOP_HOME/sbin/mr-jobhistory-daemon.sh start historyserver --config $HADOOP_CONF_DIR
        ;;

    stop)
        #Stop the ResourceManager with the following command, run on the designated ResourceManager as yarn:
        echo 'Stoping ResourceManager.'
        sudo -u $YARN_USER $HADOOP_YARN_HOME/sbin/yarn-daemon.sh --config $HADOOP_CONF_DIR stop resourcemanager
        
        #Stop the MapReduce JobHistory Server with the following command, run on the designated server as mapred:
        echo 'Stoping historyserver.'
        sudo -u $MAPRED_USER $HADOOP_HOME/sbin/mr-jobhistory-daemon.sh stop historyserver --config $HADOOP_CONF_DIR
        ;;

    *)
        echo "Usage: service hadoop-rm (start|stop)."
        ;;
esac
